# Generated by Django 4.0.4 on 2022-05-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_car', '0005_alter_carbrand_owner_alter_carmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
